config/routes.rb
PlantsIdApp::Application.routes.draw do
  root "home#index"
  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout'}

  get 'profiles/:id', to: 'profiles#show', as: 'user_profile'

  resources :events
  resources :rsvps, only: :create
  resource :profile, only: [:show, :edit, :update]
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :date, :time, :description, presence: true
  belongs_to :user
  has_many :rsvps
  has_many :users, through: :rsvps
  #Check in the rsvp table for my event id and show me all the users that are 
  #associated to my event id

end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :rsvps
  has_many :reservations, through: :rsvps, source: :event
  #source: :event is telling the app to look at the events table but we are calling it
  #reservations
  has_many :events 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :pic, PicUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find params[:id]
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.new safe_event

    if @event.save
      flash[:notice] = "Your event saved successfully"
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    @event = Event.find params[:id]
  end

  def edit
  end

  def update
    #needs to find it by id & we must update it with the the info user passed in
    event.update safe_event #.update is an active record method
    redirect_to event
  end

  private

  def safe_event
    params.require(:event).permit(:title, :description, :date, :time, :location)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    if params[:id]
      @user = User.find params[:id]
    else
      @user = current_user
    end
  end

  def edit

  end

  def update
    safe_user = params.require(:user).permit(:name, :bio, :pic)
    current_user.update safe_user
    redirect_to profile_path
  end

  #def create
  #  safe_user = params.require(:User).permit(:name, :bio, :image)
  #  user = Profile.create safe_user
  #  redirect_to user
  #end
  #

end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    event = Event.find params[:event_id]
    current_user.reservations << event
    redirect_to event, notice: "You have successfully registered for this event!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/rsvp_helper.rb
module RsvpHelper
end

app/views/events/index.html.erb
<% @events.each do |event| %>
    <div class="panel panel-warning">
      <div class="panel-heading test">
        <h3 class="panel-title"><%= event.title %></h3>
      </div>


      <div class="panel-body event">
        <div class="event-profile">
          <%= link_to image_tag(event.user.pic.thumb, {class: 'rounded-profile-pic pull-right'}), user_profile_path(event.user) %>
          <h3 class="leader">Group Leader</h3>
        </div>


        <p><%= event.date.strftime("%B %d, %Y") %></p>

        <p><%= event.time.strftime("%I:%M %P") %></p>

        <p><%= event.location %></p>

        <p><%= truncate(event.description, length: 300) %>
          <%= link_to 'See more details', event %></p>
      </div>
    </div>

<% end %>

app/views/events/new.html.erb
<div class="foreground"><h1>Add a New Event</h1>

<%= form_for @event, html: {class: "form-horizontal"} do |f| %>
    <% if @event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@event.errors.count, "error") %> prohibited
            this post from being saved:</h2>
          <ul>
            <% @event.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <h4><%= f.label :date %></h4>
    <p><%= f.date_select :date%></p>
    <h4><%= f.label :time %></h4>
    <p><%= f.time_select :time, ampm: true %></p>
    <h4><%= f.label :location %></h4>
    <p><%= f.text_field :location, class: "form-control" %>
    <h4><%= f.label :title %></h4>
    <p><%= f.text_field :title, class: "form-control" %></p>
    <h4><%= f.label :description %></h4>
    <p><%= f.text_area :description, class: "form-control" %></p>


    <h3> <%= f.submit class: 'btn btn-primary' %></h3>
<% end %>
<%= link_to 'Back to Events', events_path %>


</div>

app/views/events/show.html.erb
<div class="foreground">
  <%= button_to "Add An Event", new_event_path, method: :get, class: "btn btn-primary pull-right" %>
  <h1><%= @event.title %></h1>

  <h2>Total RSVPS: <%= @event.rsvps.count %></h2>

  <h2>Hosted by: <%= @event.user.name %></h2>

  <%= link_to image_tag(@event.user.pic.thumb, {class: 'rounded-profile-pic pull-right'}), user_profile_path(@event.user) %>
  <p><%= @event.date.strftime("%B %d, %Y") %></p>

  <p><%= @event.time.strftime("%I:%M %P") %></p>

  <p><%= @event.location %></p>

  <p><%= @event.description %>
  <h3> <%= button_to "RSVP", rsvps_path(event_id: @event.id), method: :post, class: "btn btn-primary" %></h3>


  <h6><%= link_to "Back to Event's Calendar", events_path, method: :get %></h6>
</div>

</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>EarthSource</h1>

  <h3 class="lead">Connect with Nature.</h3>
  <!--<p><a class="btn btn-lg btn-success" href="#" role="button">-->
  <%= link_to "Check Out Our Events Calendar", events_path, class: 'btn btn-lg btn-success' %>
</div>

app/views/layouts/_sign_up.html.erb
<div class="modal fade" id="sign-up">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h2 class="modal-title">Sign up</h2>
      </div>
      <div class="modal-body">
        <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
            <%= devise_error_messages! %>

            <div><%= f.label :email %>
              <br/>
              <%= f.email_field :email, :autofocus => true %></div>

            <div><%= f.label :password %>
              <br/>
              <%= f.password_field :password %></div>

            <div><%= f.label :password_confirmation %>
              <br/>
              <%= f.password_field :password_confirmation %></div>
            <br>
            <div class="submit-button"><%= f.submit "Sign up", class: "btn btn-primary" %></div>
            </br>

        <% end %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>EarthSource App</title>
  <%= stylesheet_link_tag 'application', media: 'all', "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="Yelimar Rodriguez">
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
</head>
<body id="<%= controller.controller_name %>">

<div class="container">
  <div class="header">
    <ul class="nav nav-pills pull-right">
      <li class="active"> <%= link_to "Home", root_path %></li>
      <li class="active"><%= link_to "Event Calendar", events_path %></li>
      <% if user_signed_in? %>
          <li class="active"><%= link_to "Profile", profile_path %></li>
          <li class="active"><%= link_to "Add Event", new_event_path %></li>
      <% else %>
          <li class="active"><%= link_to "Sign up", new_user_registration_path, class: "sign-up-toggle" %></li>
      <% end %>
    </ul>
    <%= link_to root_path do %>
        <h3 class="text-muted">EarthSource</h3>
    <% end %>
        <% if !user_signed_in? %>
            <p><%=link_to "Log in", new_user_session_path %></p>
        <% end %>

        </div>
        </div>

        <div class="container">
          <% if notice %>
              <p class="notice"><%= notice %></p>
          <% end %>
          <% if alert %>
              <p class="alert"><%= alert %></p>
          <% end %>

          <% if user_signed_in? %>
              <p class="welcome-message"> Welcome, <%= current_user.email %>
                 <%= link_to "Logout", destroy_user_session_path, method: :delete %></p>
          <% else %>
              <%= render 'layouts/sign_up' %>
          <% end %>


        </div>


        <div class="container">
          <%= yield %>
        </div>

app/views/profiles/edit.html.erb
<h1>Edit Your Profile!</h1>
<%= form_for current_user, url: profile_path, :html => {:multipart => true} do |f| %>
    <p><%= f.label :name %></p>
    <p><%= f.text_field :name %></p>
    <p><%= f.label :bio %></p>
    <p><%= f.text_field :bio %></p>
    <p><%= f.file_field :pic %></p>
    <p><%= f.hidden_field :pic_cache %></p>
    <p><%= f.submit %></p>
<% end %>

app/views/profiles/show.html.erb
<%= image_tag(@user.pic.thumb, {class: 'rounded-profile-pic pull-right'}) %>
<h1 class="profile-header">
  <%= @user.name %>
</h1>
<h3>Bio:</h3>
<h4> <%= @user.bio %></h4>

<h2>Hosted events</h2>
<% @user.events.each do |event| %>
    <p><%= link_to event.title, event %></p>
<% end %>

<% if @user == current_user %>
    <h2>Your RSVPS</h2>
    <% @user.rsvps.each do |rsvp| %>
        <%= link_to rsvp.event.title, rsvp.event %>
    <% end %>

    <p><%= link_to "Edit Profile", edit_profile_path %></p>
<% end %>

app/views/rsvp/index.html.erb
<h1>Rsvp#index</h1>
<p>Find me in app/views/rsvp/index.html.erb</p>